### ISSUE TITLE
Modded blocks aren't displayed on the Overlay

### ISSUE THREAD

**Issue by eldritch-cookie** [Agzam4/Mindustry-mod#3]
![2023-08-20-201848_830x425_scrot](https://github.com/Agzam4/Mindustry-mod/assets/138120879/ba828e91-95fe-40d1-b934-264d7217c17c)
as you can see the vanilla blocks show fine but the modded blocks aren't displayed

**Comment by Agzam4** [comment]
Fixed in v1.4.5

**Comment by Agzam4** [comment]
Fixed in v1.4.5
