### ISSUE TITLE
Same block is selected multiple times

### ISSUE THREAD

**Issue by 7003Mars** [Agzam4/Mindustry-mod#4]
![1](https://github.com/Agzam4/Mindustry-mod/assets/49356012/7257fb9f-f57d-4ff6-8192-b32721405b2e)
![2](https://github.com/Agzam4/Mindustry-mod/assets/49356012/59099edc-883c-4d10-b8ce-317e7032d699)
![3](https://github.com/Agzam4/Mindustry-mod/assets/49356012/065b3572-1167-49f4-967b-af10c5f8e4f9)

As the graphite press is selected twice, the calculation is twice what is actually produced (1.33/s instead of 0.67/s)

**Comment by Agzam4** [comment]
Fixed in v1.4.4
