### ISSUE TITLE
[Bug]: Processor Generator of Utilities menu does not show images of modded units

### ISSUE THREAD

**Issue by eldritch-cookie** [Agzam4/Mindustry-mod#6]
love the mod, it is in my opinion the best mindustry mod. anyways here is an image of the visual bug
![2023-09-18-154109_1917x1080_scrot](https://github.com/Agzam4/Mindustry-mod/assets/138120879/34900081-fb30-47c0-8bd8-eee116d53c34)

**Comment by Agzam4** [comment]
Fixed in `v1.6.2`
***
![image](https://github.com/Agzam4/Mindustry-mod/assets/75160721/5bfc3cec-2785-41a2-813e-7741c73ed426)
